### ISSUE TITLE
World University Rankings 2019

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#31]
Scrape https://www.timeshighereducation.com/world-university-rankings/2019/world-ranking#!/page/0/length/-1/sort_by/rank/sort_order/asc/cols/stats

**Comment by bz-hadjer** [comment]
Hi, I want to work on this,
Can you provide the layout of the csv output file and also I have 2 questions:
1. Is it necessary to use scrapy? because this task can be achieved with a small script with less than 20 lines using only the `requests` library and the built-in `csv` library.
2. Do you want the script to be adjustable to scrape the data for the current year? I mean maybe when we'll be in 2020 you want it to scrape data for 2020 and so on...

**Comment by serhii73** [comment]
Hello @bz-hadjer 
> it necessary to use scrapy? because this task can be achieved with a small script with less than 20 lines using only the requests library and the built-in csv library.

You can use any library that you want. But if it possible with python 3.7

> Do you want the script to be adjustable to scrape the data for the current year? I mean maybe when we'll be in 2020 you want it to scrape data for 2020 and so on...


Yes, if possible. It is a good possibility to scrape data for the current year.
