### ISSUE TITLE
Add black and isort

### ISSUE THREAD

**Issue by serhii73** [serhii73/place2live#48]
Add black and isort to pre-commit

**Comment by serhii73** [comment]
https://github.com/serhii73/ukrdict/issues/16#issuecomment-513534717

**Comment by serhii73** [comment]
https://github.com/asottile/reorder_python_imports

**Comment by laymonage** [comment]
Was there a reason why Black isn't used?

I see there is a badge for Black in [README.md](https://github.com/place2live/place2live/commit/2fcd6b31c8ffaf450dd93b11ee1cdce39a4a3d45) but I don't see it in the pre-commit config. If you actually want to use Black, I can create a PR that adds Black to the config and change the flake8 arguments [accordingly](https://github.com/psf/black/blob/master/.flake8) (and also remove `add-trailing-comma` because Black already handles it, albeit differently). Otherwise, I can also create a PR to remove the badge.

**Comment by serhii73** [comment]
@laymonage I think better remove the badge.
And I want to use `isort` instead `reorder`. Can you help with it?
Thank you very much!
